master > master: install methods updated

diff --git a/install/importwhales b/install/importwhales
--- a/install/importwhales
+++ b/install/importwhales
@@ -15,6 +15,7 @@ OUT="/dev/stdout";
 ERR="/dev/stderr";
 VERBOSE="/dev/null";
 VERSION="";
+LOCALDIST=".whales";
 
 #######################################
 # Methods
@@ -46,9 +47,13 @@ function import_whales_files() {
     ( $flag_examples )  && cp -r "${path}/examples"   "./.whales.examples";
     local flag_copy="-n";
     ( $flag_force ) && flag_copy="";
-    cp $flag_copy "${path}/config/.whales.env"                 ".";
-    cp $flag_copy "${path}/config/.whales.Dockerfile"          ".";
-    cp $flag_copy "${path}/config/.whales.docker-compose.yml"  ".";
+    cp $flag_copy "${path}/templates/.whales.env"                 ".";
+    cp $flag_copy "${path}/templates/.whales.Dockerfile"          ".";
+    cp $flag_copy "${path}/templates/.whales.docker-compose.yml"  ".";
+    ! [ -f ".env" ]          && cp $flag_copy "${path}/templates/.env"           ".";
+    ! [ -f ".gitignore" ]    && cp $flag_copy "${path}/templates/.gitignore"     ".";
+    ! [ -f ".dockerignore" ] && cp $flag_copy "${path}/templates/.dockerignore"  ".";
+    ! [ -d "scripts" ]       && cp $flag_copy "${path}/templates/scripts"        ".";
 
     # Output version:
     VERSION="$( cat ${path}/dist/VERSION 2> $VERBOSE || echo "{${tag}}" )";
@@ -56,10 +61,43 @@ function import_whales_files() {
     rm -rf "${dest_temp}";
 }
 
+# Creates a local copy of versions of whales
+function create_local_copy() {
+    local path="$1";
+    local tag="$2";
+    local homepath="$HOME/$LOCALDIST/$tag";
+    cli_ask_expect "Do you wish to store a local copy of the \033[92;1mwhales\033[0m:\033[1m${tag}\033[0m distribution in \033[1m${homepath}\033[0m? (y/n) " \
+        "^(y|n)$";
+    ! [ "$answer" == "y" ] && return;
+    ! [ -d "$HOME" ] && echo -e "Could not access the home directory <\033[1m${HOME}\033[0m>." >> $ERR && return;
+    ! [ -d "$HOME/$LOCALDIST" ] && mkdir "$HOME/$LOCALDIST";
+    ! [ -d "$HOME/$LOCALDIST" ] && echo -e "Could not find or create <\033[1m${HOME}/${LOCALDIST}\033[0m>." >> $ERR && return;
+    [ -d "$HOME/$LOCALDIST/$tag" ] && rm -rf "$HOME/$LOCALDIST/$tag";
+    mkdir "$HOME/$LOCALDIST/$tag";
+    ! [ -d "$HOME/$LOCALDIST/$tag" ] && echo -e "Could not find or create <\033[1m${HOME}/${LOCALDIST}/${tag}\033[0m>." >> $ERR && return;
+    cp -r "${path}/." "$HOME/.whales/$tag/";
+    echo -e "Your local distribution \033[1m${HOME}/${LOCALDIST}\033[0m now contains the following versions of \033[92;1mwhales\033[0m:  $( ls $HOME/$LOCALDIST/. 2> $VERBOSE ) ." >> $OUT;
+}
+
+# Obtain artefact from local source
+function get_artefact_from_local() {
+    local flag_force=$1;
+    local flag_templates=$2;
+    local flag_examples=$3;
+    local tag="$( echo "$4" | sed -E "s/^v([[:digit:]]+.*)$/\1/gi" )";
+    local path="$HOME/$LOCALDIST/$tag";
+    if [ "$tag" == "" ] || ! [ -d "$path" ]; then
+        echo -e "Usage: \033[1mimportwhales [--local] [--force] [--templates] [--examples] {TAG}\033[0m." >> $ERR;
+        echo -e "Valid values for \033[1m{TAG}\033[0m: the local distributions in \033[1m${HOME}/${LOCALDIST}\033[0m contains \033[92;1mwhales\033[0m: $( ls $HOME/$LOCALDIST/. 2> $VERBOSE ) ." >> $ERR;
+        exit 1;
+    fi
+    import_whales_files $flag_force $flag_templates $flag_examples "${path}";
+}
+
 # Obtain artefact from Git repository
 function get_artefact_from_repo() {
     local url_info="https://github.com/RLogik/whales/releases";
-    [ "$4" == "" ] && echo -e "Usage: \033[1mimportwhales [--force] [--templates] [--examples] {TAG}\033[0m. Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && exit 1;
+    [ "$4" == "" ] && echo -e "Usage: \033[1mimportwhales [--local] [--force] [--templates] [--examples] {TAG}\033[0m. Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && exit 1;
     !( check_curl && check_tar ) && echo -e "You need \033[1mcurl\033[0m and \033[1mtar\033[0m in order to be able to use this command." >> $ERR && exit 1;
     local flag_force=$1;
     local flag_templates=$2;
@@ -82,13 +120,14 @@ function get_artefact_from_repo() {
     ! ( $success ) && echo -e "Tagname \033[1m${tag}\033[0m could not be found! Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && rm -rf "${dest_temp}" && exit 1;
 
     local path="$( ls -d ${dest_temp}/*/ 2> $VERBOSE | head -1 | sed -E "s/\/$//" )";
+    create_local_copy "${path}" "${tag}";
     import_whales_files $flag_force $flag_templates $flag_examples "${path}";
 }
 
 # Obtain artefact via docker
 function get_artefact_via_docker() {
     local url_info="https://hub.docker.com/r/rlogik/whales/tags";
-    [ "$4" == "" ] && echo -e "Usage: \033[1mimportwhales [--force] [--templates] [--examples] {TAG}\033[0m. Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && exit 1;
+    [ "$4" == "" ] && echo -e "Usage: \033[1mimportwhales [--local] [--force] [--templates] [--examples] {TAG}\033[0m. Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && exit 1;
     local flag_force=$1;
     local flag_templates=$2;
     local flag_examples=$3;
@@ -107,6 +146,7 @@ function get_artefact_via_docker() {
     docker cp "${id}:/usr/app/whales/." "${dest_temp}";
 
     local path="${dest_temp}";
+    create_local_copy "${path}" "${tag}";
     import_whales_files $flag_force $flag_templates $flag_examples "${path}";
 
     # Cleanup
@@ -121,6 +161,16 @@ function get_artefact_via_docker() {
 
 function has_arg() {
     echo "$1" | grep -Eq "(^.*[[:space:]]|^)$2([[:space:]].*$|$)";
+}
+
+function cli_ask_expect() {
+    msg="$1";
+    patternanswer="$2";
+    answer="";
+    while ( true ); do
+        echo -ne "$msg" >> $OUT && read answer;
+        ( echo "$answer" | grep -Eq "$patternanswer" ) && break;
+    done
 }
 
 function check_curl() { ( curl --version >> $VERBOSE 2> $VERBOSE ) && return 0 || return 1; }
@@ -156,15 +206,23 @@ function check_jq() {
 
 TAG=""; [[ ${#FLAGS} -gt 0 ]] && TAG="${FLAGS[-1]}";
 ( echo "$TAG" | grep -Eq "^-+" ) && TAG="";
-flag_force=false;     ( has_arg "$SCRIPTARGS" "-+(f|force)" )           && flag_force=true;
+flag_local=false;     ( has_arg "$SCRIPTARGS" "-+(l|local)" )            && flag_local=true;
+flag_force=false;     ( has_arg "$SCRIPTARGS" "-+(f|force)" )            && flag_force=true;
 flag_templates=false; ( has_arg "$SCRIPTARGS" "-+(template|templates)" ) && flag_templates=true;
-flag_examples=false;  ( has_arg "$SCRIPTARGS" "-+(example|examples)" )  && flag_examples=true;
+flag_examples=false;  ( has_arg "$SCRIPTARGS" "-+(example|examples)" )   && flag_examples=true;
 success=0;
 check_dos2unix || success=1;
 check_jq;
 VERSION="";
-get_artefact_from_repo $flag_force $flag_templates $flag_examples "${TAG}";
+if ( $flag_local ); then
+    get_artefact_from_local $flag_force $flag_templates $flag_examples "${TAG}";
+else
+    get_artefact_from_repo $flag_force $flag_templates $flag_examples "${TAG}";
+fi
 # get_artefact_via_docker $flag_force $flag_templates $flag_examples "${TAG}";
 
 echo -e "Version \033[92;1m${VERSION}\033[0m of Whales imported." >> $OUT;
 exit $success;
+
+
+# create_local_copy "$PWD" "v0.0.3"
